"""Modifying appointment to have appointment_date and invited_user

Revision ID: 30198a96098a
Revises: 39e7786d6358
Create Date: 2021-01-30 20:36:55.664439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30198a96098a'
down_revision = '39e7786d6358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_time', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'appointment_time')
    # ### end Alembic commands ###
