"""Appointments linked to users

Revision ID: 39e7786d6358
Revises: 
Create Date: 2021-01-29 16:04:25.549986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e7786d6358'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.add_column('appointments', sa.Column('hosting_user_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('invited_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'users', ['invited_user_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'users', ['hosting_user_id'], ['id'])
    op.drop_column('appointments', 'hosting_user')
    op.drop_column('appointments', 'invited_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('invited_user', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('hosting_user', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'invited_user_id')
    op.drop_column('appointments', 'hosting_user_id')
    op.create_table('appointment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='appointment_pkey')
    )
    # ### end Alembic commands ###
